# Generated by Django 6.0 on 2025-12-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilitySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('NVD', 'NVD'), ('GITHUB', 'GitHub'), ('SNYK', 'Snyk'), ('NPM', 'npm'), ('PYPI', 'PyPI'), ('MAVEN', 'Maven'), ('RUBYGEMS', 'RubyGems'), ('GITHUB_SECURITY', 'GitHub Security'), ('GITLAB', 'GitLab Security'), ('DOCKER', 'Docker Hub')], max_length=50)),
                ('api_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('affected_packages', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectors.vulnerabilitysource')),
            ],
            options={
                'ordering': ['-published_date', '-cvss_score'],
            },
        ),
    ]
