# Generated by Django 6.0 on 2025-12-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='searchquery',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_vector',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='search_vector',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='tags',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='vulnerabilitysource',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='affected_packages',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='cve_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='cvss_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='references',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='vulnerabilitysource',
            name='api_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerabilitysource',
            name='source_type',
            field=models.CharField(max_length=50),
        ),
    ]
