// Mock data for the DevSecOps dashboard

export const vulnerabilityTrends = [
  { date: "Jan", critical: 12, high: 25, medium: 45, low: 80 },
  { date: "Fév", critical: 15, high: 30, medium: 50, low: 75 },
  { date: "Mar", critical: 8, high: 22, medium: 42, low: 70 },
  { date: "Avr", critical: 10, high: 28, medium: 48, low: 85 },
  { date: "Mai", critical: 6, high: 20, medium: 38, low: 65 },
  { date: "Juin", critical: 4, high: 18, medium: 35, low: 60 },
]

export const vulnerablePackages = [
  {
    id: 1,
    name: "lodash",
    version: "4.17.15",
    severity: "critical" as const,
    cvss: 9.8,
    cve: "CVE-2021-23337",
    language: "JavaScript",
    discovered: "2024-01-15",
    patchAvailable: true,
    affectedProjects: ["frontend-app", "api-service"],
  },
  {
    id: 2,
    name: "axios",
    version: "0.21.0",
    severity: "high" as const,
    cvss: 7.5,
    cve: "CVE-2021-3749",
    language: "JavaScript",
    discovered: "2024-01-18",
    patchAvailable: true,
    affectedProjects: ["frontend-app"],
  },
  {
    id: 3,
    name: "pillow",
    version: "8.0.0",
    severity: "high" as const,
    cvss: 7.2,
    cve: "CVE-2021-25289",
    language: "Python",
    discovered: "2024-01-20",
    patchAvailable: true,
    affectedProjects: ["ml-service", "image-processor"],
  },
  {
    id: 4,
    name: "spring-core",
    version: "5.2.0",
    severity: "critical" as const,
    cvss: 9.1,
    cve: "CVE-2022-22965",
    language: "Java",
    discovered: "2024-01-22",
    patchAvailable: true,
    affectedProjects: ["backend-api"],
  },
  {
    id: 5,
    name: "urllib3",
    version: "1.25.8",
    severity: "medium" as const,
    cvss: 5.3,
    cve: "CVE-2021-33503",
    language: "Python",
    discovered: "2024-01-25",
    patchAvailable: true,
    affectedProjects: ["data-pipeline"],
  },
  {
    id: 6,
    name: "node-fetch",
    version: "2.6.0",
    severity: "medium" as const,
    cvss: 5.9,
    cve: "CVE-2022-0235",
    language: "JavaScript",
    discovered: "2024-01-28",
    patchAvailable: false,
    affectedProjects: ["api-gateway"],
  },
]

export const pipelineHistory = [
  {
    id: "build-1234",
    name: "frontend-app",
    branch: "main",
    status: "success" as const,
    duration: "4m 32s",
    timestamp: "Il y a 12 min",
    author: "Marie D.",
    commit: "feat: add auth module",
  },
  {
    id: "build-1233",
    name: "api-service",
    branch: "develop",
    status: "failed" as const,
    duration: "2m 15s",
    timestamp: "Il y a 25 min",
    author: "Jean P.",
    commit: "fix: security patch",
  },
  {
    id: "build-1232",
    name: "ml-service",
    branch: "feature/model",
    status: "running" as const,
    duration: "1m 45s",
    timestamp: "Il y a 30 min",
    author: "Sophie L.",
    commit: "chore: update deps",
  },
  {
    id: "build-1231",
    name: "data-pipeline",
    branch: "main",
    status: "success" as const,
    duration: "6m 12s",
    timestamp: "Il y a 1h",
    author: "Pierre M.",
    commit: "feat: new ETL job",
  },
  {
    id: "build-1230",
    name: "backend-api",
    branch: "hotfix/auth",
    status: "pending" as const,
    duration: "-",
    timestamp: "Il y a 1h 15min",
    author: "Lucas R.",
    commit: "hotfix: token exp",
  },
]

export const alerts = [
  {
    id: 1,
    type: "vulnerability",
    title: "Vulnérabilité critique détectée",
    description: "lodash@4.17.15 contient une faille RCE (CVE-2021-23337)",
    severity: "critical" as const,
    timestamp: "Il y a 5 min",
    project: "frontend-app",
    actionRequired: true,
  },
  {
    id: 2,
    type: "pipeline",
    title: "Build échoué - Tests de sécurité",
    description: "Le scan SAST a détecté 3 vulnérabilités dans api-service",
    severity: "high" as const,
    timestamp: "Il y a 25 min",
    project: "api-service",
    actionRequired: true,
  },
  {
    id: 3,
    type: "supply-chain",
    title: "Package compromis détecté",
    description: "ua-parser-js@0.7.29 a été compromis (npm advisory)",
    severity: "critical" as const,
    timestamp: "Il y a 1h",
    project: "multiple",
    actionRequired: true,
  },
  {
    id: 4,
    type: "container",
    title: "Image Docker obsolète",
    description: "node:14-alpine n'est plus maintenue",
    severity: "medium" as const,
    timestamp: "Il y a 2h",
    project: "frontend-app",
    actionRequired: false,
  },
  {
    id: 5,
    type: "configuration",
    title: "Secret exposé dans le pipeline",
    description: "Une clé API a été détectée dans les logs de build",
    severity: "high" as const,
    timestamp: "Il y a 3h",
    project: "backend-api",
    actionRequired: true,
  },
]

export const dockerImages = [
  {
    id: 1,
    name: "frontend-app",
    tag: "latest",
    baseImage: "node:18-alpine",
    vulnerabilities: { critical: 0, high: 2, medium: 5, low: 12 },
    size: "245 MB",
    lastScan: "Il y a 2h",
    status: "secure" as const,
  },
  {
    id: 2,
    name: "api-service",
    tag: "v2.1.0",
    baseImage: "python:3.11-slim",
    vulnerabilities: { critical: 1, high: 3, medium: 8, low: 15 },
    size: "412 MB",
    lastScan: "Il y a 4h",
    status: "at-risk" as const,
  },
  {
    id: 3,
    name: "ml-service",
    tag: "latest",
    baseImage: "python:3.10-bullseye",
    vulnerabilities: { critical: 2, high: 5, medium: 12, low: 20 },
    size: "1.2 GB",
    lastScan: "Il y a 6h",
    status: "vulnerable" as const,
  },
  {
    id: 4,
    name: "nginx-proxy",
    tag: "stable",
    baseImage: "nginx:1.25-alpine",
    vulnerabilities: { critical: 0, high: 0, medium: 2, low: 5 },
    size: "42 MB",
    lastScan: "Il y a 1h",
    status: "secure" as const,
  },
]

export const supplyChainData = {
  nodes: [
    { id: "frontend", label: "Frontend App", risk: "medium" as const },
    { id: "api", label: "API Service", risk: "high" as const },
    { id: "ml", label: "ML Service", risk: "critical" as const },
    { id: "lodash", label: "lodash", risk: "critical" as const },
    { id: "axios", label: "axios", risk: "high" as const },
    { id: "pillow", label: "pillow", risk: "high" as const },
    { id: "npm", label: "npm Registry", risk: "low" as const },
    { id: "pypi", label: "PyPI", risk: "low" as const },
  ],
  edges: [
    { from: "frontend", to: "lodash" },
    { from: "frontend", to: "axios" },
    { from: "api", to: "axios" },
    { from: "ml", to: "pillow" },
    { from: "lodash", to: "npm" },
    { from: "axios", to: "npm" },
    { from: "pillow", to: "pypi" },
  ],
}

export const vulnerabilityByType = [
  { type: "RCE", count: 8, color: "#ef4444" },
  { type: "XSS", count: 15, color: "#f97316" },
  { type: "SQLi", count: 5, color: "#eab308" },
  { type: "SSRF", count: 3, color: "#22c55e" },
  { type: "Dep. compromise", count: 12, color: "#3b82f6" },
]

export const projectVulnerabilities = [
  { project: "frontend-app", critical: 2, high: 5, medium: 12, low: 25 },
  { project: "api-service", critical: 1, high: 8, medium: 15, low: 20 },
  { project: "ml-service", critical: 3, high: 6, medium: 10, low: 18 },
  { project: "data-pipeline", critical: 0, high: 2, medium: 8, low: 12 },
  { project: "backend-api", critical: 1, high: 4, medium: 6, low: 15 },
]
